version: '3.8'

services:
  rits-gym-reservation-bot:
    platform: linux/amd64
    image: rits-gym-reservation-bot-image
    container_name: rits-gym-reservation-bot
    build: .
    volumes:
      - .:/app
    # command: python3 /app/reservation_bot.py # デバッグ中は"docker container exec -it rits-gym-reservation-bot bash"で行く
    ports:
      - "5002:5000"
    tty: true